# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(409, 520)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../Pictures/covid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_ReporteSV = QtWidgets.QLabel(self.centralwidget)
        self.lbl_ReporteSV.setGeometry(QtCore.QRect(60, 30, 291, 41))
        self.lbl_ReporteSV.setObjectName("lbl_ReporteSV")
        self.cmbB_ReporteSV = QtWidgets.QComboBox(self.centralwidget)
        self.cmbB_ReporteSV.setGeometry(QtCore.QRect(60, 90, 291, 23))
        self.cmbB_ReporteSV.setObjectName("cmbB_ReporteSV")
        self.cmbB_ReporteSV.addItem("")
        self.btn_ReporteSV = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ReporteSV.setGeometry(QtCore.QRect(140, 130, 151, 31))
        self.btn_ReporteSV.setStyleSheet("QPushButton{\n"
"background-color:blue\n"
"border:1px\n"
"border-radius:30px\n"
"}")
        self.btn_ReporteSV.setObjectName("btn_ReporteSV")
        self.lbl_AplicativoWeb = QtWidgets.QLabel(self.centralwidget)
        self.lbl_AplicativoWeb.setGeometry(QtCore.QRect(50, 350, 311, 21))
        self.lbl_AplicativoWeb.setObjectName("lbl_AplicativoWeb")
        self.btn_AplicativoWeb = QtWidgets.QPushButton(self.centralwidget)
        self.btn_AplicativoWeb.setGeometry(QtCore.QRect(120, 400, 171, 31))
        self.btn_AplicativoWeb.setObjectName("btn_AplicativoWeb")
        self.btn_Comparar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Comparar.setGeometry(QtCore.QRect(70, 280, 91, 21))
        self.btn_Comparar.setObjectName("btn_Comparar")
        self.cmbB_Opcion1 = QtWidgets.QComboBox(self.centralwidget)
        self.cmbB_Opcion1.setGeometry(QtCore.QRect(60, 190, 111, 21))
        self.cmbB_Opcion1.setObjectName("cmbB_Opcion1")
        self.cmbB_Opcion1.addItem("")
        self.cmbB_Opcion2 = QtWidgets.QComboBox(self.centralwidget)
        self.cmbB_Opcion2.setGeometry(QtCore.QRect(60, 230, 111, 21))
        self.cmbB_Opcion2.setObjectName("cmbB_Opcion2")
        self.cmbB_Opcion2.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 409, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analisis Casos Covid"))
        self.lbl_ReporteSV.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Generar Reporte Rapido</span></p></body></html>"))
        self.cmbB_ReporteSV.setCurrentText(_translate("MainWindow", "Seleccione una Opcion..."))
        self.cmbB_ReporteSV.setItemText(0, _translate("MainWindow", "Seleccione una Opcion..."))
        self.btn_ReporteSV.setText(_translate("MainWindow", "Generar"))
        self.lbl_AplicativoWeb.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Generar Aplicativo Web</span></p></body></html>"))
        self.btn_AplicativoWeb.setText(_translate("MainWindow", "Generar"))
        self.btn_Comparar.setText(_translate("MainWindow", "Comparar"))
        self.cmbB_Opcion1.setItemText(0, _translate("MainWindow", "Seleccione una Opcion..."))
        self.cmbB_Opcion2.setItemText(0, _translate("MainWindow", "Seleccione una Opcion..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
